controllers:
- name: alex-local
  host: 0.0.0.0
  images:
    controller: "docker.io/iofog/controller-develop"
    connector: "docker.io/iofog/connector:dev"
agents:
- name: agent1
  image: "docker.io/iofog/agent:dev"
  host: 0.0.0.0
- name: agent2
  image: "docker.io/iofog/agent:dev"
  host: 0.0.0.0
microservices: []