jobs:
- job: HA
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: linux
      downloadPath: $(System.DefaultWorkingDirectory)
  - script: |
      sudo cp linux/iofogctl /usr/local/bin/
      sudo chmod 0755 /usr/local/bin/iofogctl
  - template: postinstall-steps.yaml
  - template: ssh-steps.yaml
  - template: functional-init-vm-steps.yaml
    parameters:
      id: $(jobuuid)
      distro: $(gcp.vm.distro.buster)
      repo: $(gcp.vm.repo.debian)
      agent_count: 2
      controller_count: 0
  - script: |
      gcloud --quiet container clusters get-credentials $(gcp.cluster.name) --region $(gcp.cluster.region)
    displayName: 'Connect to cluster'
  - template: configure-remote-tests.yaml
  - script: |
      sed -i "s|DB_PROVIDER=.*|DB_PROVIDER=\"postgres\"|g" test/env.sh
      sed -i "s|DB_USER=.*|DB_USER=\"$(db.user)\"|g" test/env.sh
      sed -i "s|DB_HOST=.*|DB_HOST=\"postgres-postgresql.postgres.svc.cluster.local\"|g" test/env.sh
      sed -i "s|DB_PORT=.*|DB_PORT=5432|g" test/env.sh
      sed -i "s|DB_PW=.*|DB_PW=\"$(db.pw)\"|g" test/env.sh
      sed -i "s|DB_NAME=.*|DB_NAME=\"iofog$(jobuuid)\"|g" test/env.sh
      sed -i "s|CONTROLLER_IMAGE=.*|CONTROLLER_IMAGE=\"$(enterprise_image)\"|g" test/env.sh
      cp test/env.sh test/conf
      cat test/conf/env.sh
    displayName: 'Set up Postgres on K8s cluster'
  - template: install-test-deps.yaml
  - script: |
      set -o pipefail
      test/run.bash functional-ha | tee test/conf/results-functional-ha.tap
    displayName: 'Run Functional Tests'
  - script: |
      tap-junit -i test/conf/results-functional-ha.tap -o test/conf -s HA -n results-functional-ha.xml || true
    displayName: 'Convert test output from TAP to JUnit'
    condition: succeededOrFailed()
  - script: |
        test/clean.bash $(jobuuid)
    displayName: 'Clean K8s Cluster'
    condition: always()
  - template: functional-post-test.yaml
  - template: functional-clean-vm.yaml
    parameters:
      id: $(jobuuid)
      agent_count: 2
      controller_count: 0
